@startuml
left to right direction
skinparam actorPosition top
skinparam actorStyle awesome

actor Administrador as A
actor Usuario as U

rectangle "Sistema de Controle de Empréstimo de Materiais do Campus" {
  
  usecase "Cadastrar Empréstimo" as CE1
  usecase "Cadastrar entrada de Material" as CE2
  usecase "Cadastrar saida de Material" as CE3
  usecase "Cadastrar Usuário" as CE4
  usecase "Socilitar um Empréstimo" as CE5
  usecase "Cadastrar Administrador" as CE6
  usecase "Verificar Disponibilidade do Material" as CE7
  usecase "Cadastrar Objeto Achado" as CO1
  usecase "Cadastrar Saida do Objeto" as CO2
  

  A --> CE1
  A --> CE2
  A --> CE3
  A --> CE4
  A --> CO1
  A --> CO2

  
  U --> CE5

  CE1 .-> CE5 : <<include>>
  CE5 .-> CE7 : <<include>>
  CE5 .-> CE4 : <<extend>>
}

@enduml