@startuml
left to right direction
actor Administrador
actor "Usuário" as Usuario

rectangle "Sistema de Controle de Materiais" {
    usecase "Cadastrar Administrador" as UC1
    usecase "Cadastrar Material de Uso Coletivo" as UC2
    usecase "Registrar Empréstimo de Material" as UC3
    usecase "Controlar Entrada/Saída de Materiais" as UC4
    usecase "Cadastrar Objeto Achado" as UC5
    usecase "Registrar Retirada de Objeto Achado" as UC6
    usecase "Controlar Entrada/Saída de Objetos Achados" as UC7
    usecase "Autenticar Administrador" as UC8
}

Administrador --> UC1
Administrador --> UC2
Administrador --> UC3
Administrador --> UC4
Administrador --> UC5
Administrador --> UC7
Administrador --> UC8
Administrador --> UC6

Usuario --> UC3 : solicita
Usuario --> UC6 : retira

UC4 .-> UC3 : <<include>>
UC3 .-> UC2 : <<include>>

UC7 .-> UC6 : <<include>>
UC6 .-> UC5 : <<include>>

@enduml